### ISSUE TITLE
Define authorization tests for the ESCAPE Datalake

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/escape-auth-tests#2]
# Goal

Assess datalake sites compliance with ESCAPE namespace authorization proposal

# Tasks

- [ ] Add the ability to test multiple datalake endpoints
- [ ] Provide integrated report of test results

## Tests

- [ ] Verify read access to ESCAPE storage area is granted to members of the `/escape` group
